source "https://rubygems.org"

gem "fastlane", "~> 2.222" # bản ổn định, tương thích Ruby 3.4
gem "abbrev"               # fix cảnh báo thiếu abbrev
gem "ostruct"              # fix cảnh báo thiếu ostruct