source "https://rubygems.org"

gem "fastlane", "~> 2.222" # bản ổn định, tương thích Ruby 3.4
gem "abbrev"               # fix cảnh báo thiếu abbrev
gem "ostruct"              # fix cảnh báo thiếu ostruct
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
